title: QoutaID Docs
description: Dokumentasi resmi QoutaID
remote_theme: just-the-docs/just-the-docs

baseurl: ""
url: "https://git.qouta.id"

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive

# Heading anchor links
heading_anchors: true

# Footer
footer_content: "Copyright QoutaID. Distributed under the <a href=\"https://github.com/QoutaID/qoutaid.github.io/blob/main/LICENSE\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Kembali ke atas"

# Color scheme (light/dark)
color_scheme: light

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/QoutaID"

aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: QoutaID
    url: https://qouta.id
    hide_icon: false

# Plugins
plugins:
  - jekyll-seo-tag
